SKILL_CATALOG = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express",
    "FastAPI",
    "Django",
    "Flask",
    "Spring Boot",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Redis",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Git",
    "GitHub Actions",
    "CI/CD",
    "REST API",
    "GraphQL",
    "Tailwind CSS",
    "HTML",
    "CSS",
    "SASS",
    "Figma",
    "Power BI",
    "Tableau",
    "SQL",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Data Analysis",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "OpenAI",
    "LangChain",
    "Prompt Engineering",
    "Agile",
    "Scrum",
    "Leadership",
    "Communication",
    "Product Management",
    "Testing",
    "Pytest",
    "Jest",
    "Playwright",
    "Selenium",
    "Linux",
    "Bash",
]

SECTION_ALIASES = {
    "skills": ["skills", "technical skills", "core skills", "competencies"],
    "education": ["education", "academic background", "academics"],
    "experience": [
        "experience",
        "work experience",
        "professional experience",
        "employment history",
        "career history",
    ],
}

DEGREE_HINTS = (
    "bachelor",
    "master",
    "b.tech",
    "btech",
    "m.tech",
    "phd",
    "mba",
    "b.sc",
    "m.sc",
    "b.e",
    "university",
    "college",
    "school",
)

STOP_WORDS = {
    "about",
    "across",
    "after",
    "also",
    "analyze",
    "and",
    "application",
    "applications",
    "build",
    "building",
    "candidate",
    "collaboration",
    "communication",
    "company",
    "customers",
    "data",
    "deliver",
    "design",
    "development",
    "engineer",
    "engineering",
    "experience",
    "for",
    "from",
    "have",
    "high",
    "ideal",
    "improve",
    "in",
    "including",
    "job",
    "knowledge",
    "looking",
    "maintain",
    "management",
    "must",
    "need",
    "our",
    "performance",
    "product",
    "quality",
    "responsibilities",
    "role",
    "skills",
    "solutions",
    "strong",
    "team",
    "technical",
    "the",
    "their",
    "through",
    "with",
    "work",
    "working",
    "years",
    "you",
    "your",
}
